In [11]:
from PIL import Image
import numpy as np
import scipy.ndimage
import math

In [12]:
# reading original image
# default format for this is "uint8"
img = np.array(Image.open('C:/Users/Cem/Documents/GitHub/Multimedia-Workspace/HW1/Lena.gif'))

print(img.dtype, "   ", img.shape)
print(img)

uint8     (256, 256)
[[137 136 133 ... 145 148 114]
 [137 136 133 ... 145 148 114]
 [138 133 134 ... 133 125  87]
 ...
 [ 28  28  29 ...  53  62  59]
 [ 20  25  26 ...  64  69  65]
 [ 22  30  25 ...  71  68  72]]


In [13]:
# converting from type "uint8" to "double" format
_img = img.astype(np.float64)

print(_img)

[[137. 136. 133. ... 145. 148. 114.]
 [137. 136. 133. ... 145. 148. 114.]
 [138. 133. 134. ... 133. 125.  87.]
 ...
 [ 28.  28.  29. ...  53.  62.  59.]
 [ 20.  25.  26. ...  64.  69.  65.]
 [ 22.  30.  25. ...  71.  68.  72.]]


In [14]:
# declaring filter array full of 1/25 values
lowpass_filter = np.full((5, 5), 1/25)

print(lowpass_filter)

[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]


In [15]:
# equivalent function to "imfilter" in MATLAB
# to handle replicate mode with image converted to double format
# using low pass filter
filtered_img = scipy.ndimage.correlate(_img, lowpass_filter, mode='nearest').transpose()

print(filtered_img)

[[136.04 135.44 134.24 ...  25.64  24.92  24.6 ]
 [135.72 135.04 133.92 ...  26.24  25.68  25.44]
 [135.8  135.12 134.12 ...  28.16  27.6   27.2 ]
 ...
 [121.72 109.88  92.72 ...  50.2   56.84  61.44]
 [124.96 109.52  89.12 ...  54.16  60.56  65.24]
 [122.36 105.08  83.92 ...  57.8   63.48  67.4 ]]


In [16]:
# calculation for MSE
N1, N2 = _img.shape[0], _img.shape[1]
MSE = 0

for i in range(N1):
    for j in range(N2):
        difference = filtered_img[i][j] - _img[i][j]
        MSE += pow(difference, 2)

MSE = MSE / (N1*N2)

In [17]:
# calculation for PSNR
tmp_var = (pow(255, 2) / MSE)
PSNR = 10 * math.log10(tmp_var)

In [18]:
PSNR

11.603151799825524

In [21]:
print("{:10.2f}".format(PSNR))

     11.60
