In [25]:
from PIL import Image
import numpy as np
import scipy.ndimage
import math

In [26]:
# reading original image
# default format for this is "uint8"
img = np.array(Image.open('C:/Users/Cem/Documents/GitHub/Multimedia-Workspace/HW1/Lena.gif'))

print(img.dtype, "   ", img.shape)
print(img)

uint8     (256, 256)
[[137 136 133 ... 145 148 114]
 [137 136 133 ... 145 148 114]
 [138 133 134 ... 133 125  87]
 ...
 [ 28  28  29 ...  53  62  59]
 [ 20  25  26 ...  64  69  65]
 [ 22  30  25 ...  71  68  72]]


In [27]:
# converting from type "uint8" to "double" format
_img = img.astype(np.float64)

print(_img)

[[137. 136. 133. ... 145. 148. 114.]
 [137. 136. 133. ... 145. 148. 114.]
 [138. 133. 134. ... 133. 125.  87.]
 ...
 [ 28.  28.  29. ...  53.  62.  59.]
 [ 20.  25.  26. ...  64.  69.  65.]
 [ 22.  30.  25. ...  71.  68.  72.]]


In [28]:
# declaring filter array full of 1/9 values
lowpass_filter = np.full((3, 3), 1/9)

print(lowpass_filter)

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]


In [35]:
# equivalent function to "imfilter" in MATLAB
# to handle replicate mode with image converted to double format
# using low pass filter
filtered_img = scipy.ndimage.correlate(_img, lowpass_filter, mode='nearest').transpose()

print(filtered_img)

[[136.66666667 136.55555556 135.33333333 ...  25.          24.77777778
   23.66666667]
 [135.33333333 135.22222222 134.44444444 ...  26.33333333  25.88888889
   25.        ]
 [135.         134.55555556 133.55555556 ...  27.33333333  27.11111111
   26.77777778]
 ...
 [138.66666667 134.         109.77777778 ...  50.88888889  60.33333333
   65.77777778]
 [135.66666667 128.77777778  99.44444444 ...  57.44444444  64.77777778
   68.88888889]
 [125.33333333 116.77777778  86.55555556 ...  59.77777778  65.66666667
   69.22222222]]


In [30]:
# calculation for MSE
N1, N2 = _img.shape[0], _img.shape[1]
MSE = 0

for i in range(N1):
    for j in range(N2):
        difference = filtered_img[i][j] - _img[i][j]
        MSE += pow(difference, 2)

MSE = MSE / (N1*N2)

In [33]:
# calculation for PSNR
tmp_var = (pow(255, 2) / MSE)
PSNR = 10 * math.log10(tmp_var)

In [34]:
PSNR

11.452751514291483